name: Build and Deploy to Container App

on:
  workflow_dispatch:
permissions:
  id-token: write

jobs:
  build:
    name: Build and test solution
    runs-on: ubuntu-latest

    steps:
    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: 12172ac4-726b-4c16-9505-eb8dc39c3ee5
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build with dotnet
      run: dotnet build --no-restore
      
    - name: Get Latest Container Image Tag
      id: get_tag
      run: |
        TAG=$(az acr repository show-tags --name microhackregistry --repository microhackapp --orderby time_desc --output tsv --detail | head -n 1 | awk '{print $4}')
        NUMERIC_TAG=$(echo "$TAG" | grep -oE '[0-9]+')
        INCREMENTED_TAG=$((NUMERIC_TAG + 1))
        UPDATED_TAG=$(echo "$TAG" | sed "s/$NUMERIC_TAG/$INCREMENTED_TAG/")
        echo "image_tag=$UPDATED_TAG" >> $GITHUB_OUTPUT
    - name: Checkout repository
      uses: actions/checkout@v4
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
          dotnet-version: 8.0.x
          
    - name: Restore dependencies
      run: dotnet restore
        
    - name: Build with dotnet
      run: dotnet build --no-restore
    - name: Build and Push Image
      run: |
          az acr login --name microhackuser14 --username ${{ secrets.ACR_USERNAME }} --password ${{ secrets.ACR_PASSWORD }} &&
          docker build -t microhackuser14.azurecr.io/microhackapp:1 -f Dockerfile . &&
          docker push microhackuser14.azurecr.io/microhackapp:1
